// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZYivFWS0u-KyAPNh5WqBM2UgpJS5Ogj0',
    appId: '1:600457798477:android:190d41a07dd35ca5948d04',
    messagingSenderId: '600457798477',
    projectId: 'maple-rides',
    storageBucket: 'maple-rides.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7_LiEtqRBbzFovVWrJczhmFJTIW6YJwo',
    appId: '1:600457798477:ios:34e8433b7e66a460948d04',
    messagingSenderId: '600457798477',
    projectId: 'maple-rides',
    storageBucket: 'maple-rides.firebasestorage.app',
    androidClientId: '600457798477-3ki13e5k2un5ek1gkqq6cad8ai4j3eqm.apps.googleusercontent.com',
    iosClientId: '600457798477-msjkc01tcsfc0069g4hl4bukspf30l1v.apps.googleusercontent.com',
    iosBundleId: 'com.cabme.driver.ios',
  );

}